### ISSUE TITLE
Compiling buffered_producer_example.cpp: /usr/bin/ld: /tmp/ccjwsh8i.o: undefined reference to symbol 'rd_kafka_topic_name'

### ISSUE THREAD

**Issue by marcoippolito** [mfontanini/cppkafka#132] opened 2018-11-03 08:03 UTC
Hi,
trying to compile buffered_producer_example.cpp:

    `g++ -std=c++17 -lrdkafka -lz -lstdc++ buffered_producer_example.cpp -lboost_program_options 
    -lcppkafka -obuffered_producer_example
    /usr/bin/ld: /tmp/ccjwsh8i.o: undefined reference to symbol 'rd_kafka_topic_name'
    //usr/local/lib/librdkafka.so: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    `

What am I missing?
Looking forward to your kind help.
Marco

**Comment by mfontanini** [comment] 2018-11-03 14:57
If you run `make examples`, that will build it. The issue is you're linking first with rdkafka and then with cppkafka. It should be the other way.

**Comment by j-fab** [comment] 2019-01-07 07:08
I am sorry but I encounter the same issue. 
Whenever I create the BufferedProducer, I have this error. 
I also create BufferedProducer in your examples/producer_example.cpp, and have the same error. 
Could you tell me how I can use this class?

**Comment by mfontanini** [comment] 2019-01-07 17:10
How are you building your code?

**Comment by j-fab** [comment] 2019-01-08 02:51
I make install librdkafka, and I download cppkafka-0.2.tar.gz, make install cppkafka
I then have /usr/local/lib/libcppkafka.so and I set target_link_libraries to it. 
After these, I build and run examples/consumer_example and producer_example successfully, and I can include the .h files and create consumer and producer objects in my application successfully, however, I just cannot create this BufferedProducer, neither in my application nor from a single buffered_producer_example, because of this error. 
Sorry my question might be naive, I am not good at compile and build, and thanks for your prompt reply :)

**Comment by mfontanini** [comment] 2019-01-08 02:55
Are you doing `target_link_libraries(something cppkafka rdkafka)`? rdkafka has to go _after_ cppkafka. This should work, the tests use the buffered producer and it works fine so you're likely doing something wrong.

**Comment by j-fab** [comment] 2019-01-08 06:11
I was doing target_link_libraries(something cppkafka). I make it target_link_libraries(something cppkafka rdkafka) now and it works. Thanks a lot!

**Comment by mfontanini** [comment] 2019-01-08 17:42
Cool, no problem! I'm closing this as it's a non issue.

**Closed by mfontanini** 2019-01-08 17:42 UTC
