### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by shobhitjdpsr** [mfontanini/cppkafka#205] opened 2019-07-01 17:26 UTC
I am on Ubuntu, I tried following:-
1) mkdir build 
2)cd build
3)cmake
4)make install
5)make

This was done successfully

Then while trying to run following code:-
#include <cppkafka/cppkafka.h>

// #include <librdkafka/rdkafkacpp.h>

using namespace std;
using namespace cppkafka;

int main() {
    // Create the config
   cppkafka::Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092" }
    };

    // Create the producer
    cppkafka::Producer producer(config);

    // Produce a message!
    string message = "hey there!";
    producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
    producer.flush();

return 0;

}

I used following command on terminal:-

sudo g++ alt.cpp  -std=c++11 -I /usr/local/include/cppkafka  -I/usr/include -L/usr/local/lib/librdkafka++.so -lrdkafka++ -lpthread 

Then I get the following errors:-
/tmp/ccg0ZYco.o: In function `main':
alt.cpp:(.text+0x105): undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption(std::string const&, char const*)'
alt.cpp:(.text+0x137): undefined reference to `cppkafka::Configuration::Configuration(std::initializer_list<cppkafka::ConfigurationOption> const&)'
alt.cpp:(.text+0x1ac): undefined reference to `cppkafka::Producer::Producer(cppkafka::Configuration)'
alt.cpp:(.text+0x20d): undefined reference to `cppkafka::Buffer::Buffer(std::string const&)'
alt.cpp:(.text+0x28e): undefined reference to `cppkafka::Producer::produce(cppkafka::MessageBuilder const&)'
alt.cpp:(.text+0x2ca): undefined reference to `cppkafka::Producer::flush()'
/tmp/ccg0ZYco.o: In function `cppkafka::BasicMessageBuilder<cppkafka::Buffer, cppkafka::MessageBuilder>::BasicMessageBuilder(std::string)':
alt.cpp:(.text._ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC2ESs[_ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC5ESs]+0x55): undefined reference to `cppkafka::Buffer::Buffer()'
alt.cpp:(.text._ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC2ESs[_ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC5ESs]+0x75): undefined reference to `cppkafka::Buffer::Buffer()'
collect2: error: ld returned 1 exit status

While trying to run this code on  the terminal :- 
#include <cppkafka/cppkafka.h>

// #include <librdkafka/rdkafkacpp.h>

using namespace std;
using namespace cppkafka;

int main() {
    // Create the config
   Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092" }
    };

    // Create the producer
   Producer producer(config);

    // Produce a message!
    string message = "hey there!";
    producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
    producer.flush();

return 0;

}

Using this command on terminal:-

sudo g++ alt.cpp  -std=c++11 -I /usr/local/include/cppkafka  -I/usr/include -L/usr/local/lib/librdkafka++.so -lrdkafka++ -lpthread 

I get following error
tmp/ccmlKvit.o: In function `main':
alt.cpp:(.text+0x105): undefined reference to `cppkafka::ConfigurationOption::ConfigurationOption(std::string const&, char const*)'
alt.cpp:(.text+0x137): undefined reference to `cppkafka::Configuration::Configuration(std::initializer_list<cppkafka::ConfigurationOption> const&)'
alt.cpp:(.text+0x1ac): undefined reference to `cppkafka::Producer::Producer(cppkafka::Configuration)'
alt.cpp:(.text+0x20d): undefined reference to `cppkafka::Buffer::Buffer(std::string const&)'
alt.cpp:(.text+0x28e): undefined reference to `cppkafka::Producer::produce(cppkafka::MessageBuilder const&)'
alt.cpp:(.text+0x2ca): undefined reference to `cppkafka::Producer::flush()'
/tmp/ccmlKvit.o: In function `cppkafka::BasicMessageBuilder<cppkafka::Buffer, cppkafka::MessageBuilder>::BasicMessageBuilder(std::string)':
alt.cpp:(.text._ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC2ESs[_ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC5ESs]+0x55): undefined reference to `cppkafka::Buffer::Buffer()'
alt.cpp:(.text._ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC2ESs[_ZN8cppkafka19BasicMessageBuilderINS_6BufferENS_14MessageBuilderEEC5ESs]+0x75): undefined reference to `cppkafka::Buffer::Buffer()'
collect2: error: ld returned 1 exit status

Can someone please guide what else can be done

**Comment by mfontanini** [comment] 2019-07-01 17:27
Did you run `sudo ldconfig`? Otherwise it will fail to find the right symbols.

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:28
No I did not use. Should I uninstall it and then do? or should i do it now in terminal of build folder?

**Comment by mfontanini** [comment] 2019-07-01 17:29
Just run `sudo ldconfig` in any directory, that affects a sort of global cache of shared libraries. This is not `cppkafka` specific, it will happen for any library you build and install manually.

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:31
I just did it still getting same error.
What else can be done?

**Comment by mfontanini** [comment] 2019-07-01 17:32
Okay, now looking at your build command, you're not doing `-lcppkafka`...

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:32
![sj](https://user-images.githubusercontent.com/20614765/60455545-3bde5080-9bfc-11e9-843e-e4d3a058ce70.png)

**Comment by mfontanini** [comment] 2019-07-01 17:32
`-L/usr/local/lib/librdkafka++.so -lrdkafka++` < that's the wrong library. That's rdkafka++, not cppkafka.

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:34
![sjjj](https://user-images.githubusercontent.com/20614765/60455628-81028280-9bfc-11e9-98d5-0a9539fc9764.png)

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:34
What can be done now? I tried -lcppkafka also

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:46
Anything else that you my recommend for me to try to make this work ?

**Comment by mfontanini** [comment] 2019-07-01 17:56
* Rebuild from scratch and `make install`
* Run `sudo ldconfig`
* Remove any references to rdkafka++ in your build command
* Don't use -L with a file, it takes a directory. In this case since you're installing in a standard location (`/usr/local`), this is useless. Just doing `-lcppkafka` works.
* Link with `rdkafka` too. This has to be done *after* the option to link with cppkafka. e.g. `-lcppkafka -lrdkafka`. This will otherwise cause some link issue eventually.

Many of those won't fix it but those are all issues.

**Comment by shobhitjdpsr** [comment] 2019-07-01 17:57
While rebuilding from scratch, what order of commands would you recommend, is this correct order:- 
mkdir build
2)cd build
3)cmake
4)make install
5)make

**Comment by mfontanini** [comment] 2019-07-01 18:00
This is covered in [the README file](https://github.com/mfontanini/cppkafka#compiling). Installing comes after building it.

**Comment by shobhitjdpsr** [comment] 2019-07-01 18:51
![kjh](https://user-images.githubusercontent.com/20614765/60459589-320e1a80-9c07-11e9-813c-d0016d8381d2.png)
![hjv](https://user-images.githubusercontent.com/20614765/60459618-46eaae00-9c07-11e9-9b7b-014df8dce06f.png)


I tried the steps mentioned by you by rebuilding and using sudo ldconfig, but still have the following errrors. 

Please suggest what can be done now

**Comment by shobhitjdpsr** [comment] 2019-07-01 18:53
![ghj](https://user-images.githubusercontent.com/20614765/60459745-95984800-9c07-11e9-81f4-58b73a6c797f.png)

**Comment by mfontanini** [comment] 2019-07-01 18:54
Don't keep adding `rdkafka++`, that won't fix anything. What's the output of `ldd a.out`? You should really try to do some troubleshooting on your own, this is not a problem with the library but with your setup instead.

**Comment by shobhitjdpsr** [comment] 2019-07-01 19:20
I removed rdkafka++, still same issues, I dont know why. I tried troubleshooting but nothing working out.
Check this out:-
![sjsj](https://user-images.githubusercontent.com/20614765/60461172-67b50280-9c0b-11e9-8b2c-817bbaadb8f4.png)

**Comment by shobhitjdpsr** [comment] 2019-07-01 19:37
It gives the following error after trying the above steps:-
error while loading shared libraries: libcppkafka.so.0.3.1: cannot open shared object file: No such file or directory

**Comment by accelerated** [comment] 2019-07-01 19:40
Make sure your compiled cppkafka.a/so is in your LD_LIBRARY_PATH or add it on the command line via -L<path_to_binary>

**Comment by shobhitjdpsr** [comment] 2019-07-01 19:48
@accelerated  Where am I likely to find the same, I am unable to find the same on my system (cppkafka.a/so)

**Comment by mfontanini** [comment] 2019-07-01 19:52
`/usr/local/lib`

**Comment by shobhitjdpsr** [comment] 2019-07-01 20:29
![duhghjksd](https://user-images.githubusercontent.com/20614765/60464712-f67a4d00-9c14-11e9-9a56-81c98e72272f.png)


It is not showing up, please see

**Comment by mfontanini** [comment] 2019-07-01 20:34
Did you run `sudo make install` and it didn't fail? I think the file is actually going to be under `/usr/local/lib64` as per @accelerated _recent_ changes. Can you try to find using `find /usr/local -name libcppkafka*`?

**Comment by mfontanini** [comment] 2019-07-01 20:38
@accelerated is there any real benefit on having things installed under `lib64`? I don't seem to have any libraries under `/usr/lib64` nor `/usr/local/lib64` so I wonder if this isn't just making finding the library more complicated. I'm going to guess @shobhitjdpsr doesn't have lib64 in LD_LIBRARY_PATH.

@shobhitjdpsr can you run `LD_LIBRARY_PATH=/usr/local/lib64 ./a.out` if you do find the files under `/usr/local/lib64`?

**Comment by shobhitjdpsr** [comment] 2019-07-01 20:43
![fgu](https://user-images.githubusercontent.com/20614765/60465473-cb90f880-9c16-11e9-98e3-e97364d53902.png)
[](url)
![ghj](https://user-images.githubusercontent.com/20614765/60465542-f7ac7980-9c16-11e9-96be-16274b21d539.png)

**Comment by mfontanini** [comment] 2019-07-01 20:43
Okay I can confirm that's the case in my setup as well, I also manage to build/link but when I run it, it can't find the lib. So basically this only works if you provide an LD_LIBRARY_PATH pointing to `/usr/local/lib64` which is broken. @shobhitjdpsr ignore my comment, this isn't broken just for you.

**Comment by shobhitjdpsr** [comment] 2019-07-01 20:43
Hi I did find it in lib64, but still it has some error, what else can be tried?

**Comment by mfontanini** [comment] 2019-07-01 20:44
You can run it by doing `LD_LIBRARY_PATH=/usr/local/lib64 ./a.out` but we should fix that, users shouldn't have to use `LD_LIBRARY_PATH` unless they're installing in non-standard locations.

**Comment by shobhitjdpsr** [comment] 2019-07-01 20:47
![fghgn](https://user-images.githubusercontent.com/20614765/60465735-70abd100-9c17-11e9-97ec-cb9c91921146.png)


Any idea why this error might have come?

**Comment by mfontanini** [comment] 2019-07-01 20:49
You need to provide the right endpoint for the kafka brokers. Are you running a kafka server?

Anyway, that means you managed to run it. I've temporarily removed putting the library under `lib64` when installing on 18d0b0c00be82cd64cc4f24fb26cd6ed59e0e5b0, but we should figure out how to do this properly. @accelerated I presume you're using this so please expand on why we need it.

@shashank88 if you make a clean build by removing `build`, then re-running all commands including install, then run `sudo ldconfig` and build you application, you should be able to run it without providing `LD_LIBRARY_PATH`.

**Comment by shobhitjdpsr** [comment] 2019-07-01 20:51
@mfontanini Since it is running is it necessary to do the same (CLEAN BUILD)?

**Comment by mfontanini** [comment] 2019-07-01 20:54
(you should also pull from the repo to get that last commit). You don't _have_ to but you'll always have to run your app using `LD_LIBRARY_PATH` which is annoying. If you're okay with that, then don't pull/rebuild.

**Comment by shobhitjdpsr** [comment] 2019-07-01 21:25
My Kafka server is up.I am able to send from other python system to the same server. But, on my system  still I am getting some error. What may be wrong?

I personally suspect some problem with "metadata.broker.list". what is it actually for? Do you think that might be a problem?

[my server is on 192.168.1.4 and port is 9092]


![ghj](https://user-images.githubusercontent.com/20614765/60467585-9c7d8580-9c1c-11e9-916c-b6dbbd0bec51.png)

**Comment by shobhitjdpsr** [comment] 2019-07-01 21:38
@mfontanini  What would you suggest for the same?

**Comment by mfontanini** [comment] 2019-07-01 21:54
Yes, that's how you specify the kafka broker(s) endpoint(s). If you put the wrong endpoint there it won't work.

**Closed** 2019-07-02 15:12 UTC
